'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Mic, MicOff, Phone, PhoneCall, PhoneOff, Volume2, X } from 'lucide-react';
import { toast } from 'sonner';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

type CallState = 'idle' | 'calling' | 'incoming' | 'connected';
type Signal = { type: 'ring' | 'offer' | 'answer' | 'ice' | 'hangup' | 'decline'; from: string; to: string; callId: string; offer?: RTCSessionDescriptionInit; answer?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit };

function makeCallId() { return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`; }
function roomFor(a: string, b: string) { return `majaay-audio-call-${[a, b].sort().join('-')}`; }

export function AudioCallOverlay({ userId, otherUserId, otherName, active, onClose }: { userId: string; otherUserId?: string | null; otherName: string; active: boolean; onClose?: () => void }) {
  const [state, setState] = useState<CallState>('idle'); const [muted, setMuted] = useState(false); const [elapsed, setElapsed] = useState(0); const [callId, setCallId] = useState<string | null>(null); const [client, setClient] = useState<SupabaseClient | null>(null);
  const channelRef = useRef<ReturnType<SupabaseClient['channel']> | null>(null); const pcRef = useRef<RTCPeerConnection | null>(null); const localStreamRef = useRef<MediaStream | null>(null); const remoteAudioRef = useRef<HTMLAudioElement>(null); const pendingIceRef = useRef<RTCIceCandidateInit[]>([]);
  const room = useMemo(() => otherUserId ? roomFor(userId, otherUserId) : null, [userId, otherUserId]);
  useEffect(() => { if (!active || client) return; let cancelled = false; fetch('/api/realtime-config', { cache: 'no-store' }).then((response) => response.json()).then((config) => { if (!cancelled && config.url && config.anonKey) setClient(createClient(config.url, config.anonKey, { auth: { persistSession: false, autoRefreshToken: false } })); }).catch(() => undefined); return () => { cancelled = true; }; }, [active, client]);

  const cleanupPeer = useCallback(() => { pcRef.current?.close(); pcRef.current = null; localStreamRef.current?.getTracks().forEach((track) => track.stop()); localStreamRef.current = null; pendingIceRef.current = []; setMuted(false); setElapsed(0); }, []);
  const closeCall = useCallback((notify = true) => { const current = callId; if (notify && channelRef.current && current && room) void channelRef.current.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'hangup', from: userId, to: otherUserId, callId: current } satisfies Signal }); cleanupPeer(); setCallId(null); setState('idle'); onClose?.(); }, [callId, cleanupPeer, onClose, otherUserId, room, userId]);

  const ensurePeer = useCallback(async (id: string) => { if (pcRef.current) return pcRef.current; const pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:stun.cloudflare.com:3478' }] }); pc.onicecandidate = (event) => { if (event.candidate && channelRef.current && room) void channelRef.current.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'ice', from: userId, to: otherUserId, callId: id, candidate: event.candidate.toJSON() } satisfies Signal }); }; pc.ontrack = (event) => { if (remoteAudioRef.current && event.streams[0]) { remoteAudioRef.current.srcObject = event.streams[0]; void remoteAudioRef.current.play().catch(() => undefined); } }; pc.onconnectionstatechange = () => { if (pc.connectionState === 'connected') setState('connected'); if (['failed', 'disconnected', 'closed'].includes(pc.connectionState)) closeCall(false); }; const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true }, video: false }); stream.getTracks().forEach((track) => pc.addTrack(track, stream)); localStreamRef.current = stream; pcRef.current = pc; return pc; }, [closeCall, otherUserId, room, userId]);

  useEffect(() => { if (!active || !room || !client || !otherUserId) return; const channel = client.channel(room, { config: { broadcast: { self: false } } }); channelRef.current = channel; const receive = async ({ payload }: { payload: Signal }) => { if (!payload || payload.to !== userId || (callId && payload.callId !== callId)) return; if (payload.type === 'ring') { setCallId(payload.callId); setState('incoming'); return; } if (payload.type === 'hangup' || payload.type === 'decline') { cleanupPeer(); setCallId(null); setState('idle'); toast.info(payload.type === 'decline' ? 'Appel refusé.' : 'Appel terminé.'); onClose?.(); return; } try { if (payload.type === 'offer') { setCallId(payload.callId); const pc = await ensurePeer(payload.callId); await pc.setRemoteDescription(payload.offer!); for (const candidate of pendingIceRef.current) await pc.addIceCandidate(candidate).catch(() => undefined); pendingIceRef.current = []; const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); setState('connected'); await channel.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'answer', from: userId, to: otherUserId, callId: payload.callId, answer } satisfies Signal }); } else if (payload.type === 'answer' && pcRef.current) { await pcRef.current.setRemoteDescription(payload.answer!); setState('connected'); } else if (payload.type === 'ice' && payload.candidate) { if (pcRef.current?.remoteDescription) await pcRef.current.addIceCandidate(payload.candidate).catch(() => undefined); else pendingIceRef.current.push(payload.candidate); } } catch { toast.error('Connexion audio impossible. Vérifie l’autorisation du microphone et réessaie.'); closeCall(false); } }; channel.on('broadcast', { event: 'call-signal' }, receive).subscribe(); return () => { channel.unsubscribe(); channelRef.current = null; cleanupPeer(); }; }, [active, callId, cleanupPeer, closeCall, client, ensurePeer, onClose, otherUserId, room, userId]);

  const startCall = async () => { if (!room || !otherUserId || !client) return toast.error('Le service d’appel Majay est encore en connexion. Réessaie dans un instant.'); if (!navigator.mediaDevices?.getUserMedia) return toast.error('Ce navigateur ne prend pas en charge les appels audio IP.'); try { const id = makeCallId(); setCallId(id); setState('calling'); const pc = await ensurePeer(id); await channelRef.current?.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'ring', from: userId, to: otherUserId, callId: id } satisfies Signal }); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); await channelRef.current?.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'offer', from: userId, to: otherUserId, callId: id, offer } satisfies Signal }); } catch { toast.error('Impossible de démarrer l’appel. Autorise le microphone puis réessaie.'); closeCall(false); } };
  const acceptCall = async () => { setState('calling'); };
  const declineCall = () => { if (channelRef.current && callId && room) void channelRef.current.send({ type: 'broadcast', event: 'call-signal', payload: { type: 'decline', from: userId, to: otherUserId, callId } satisfies Signal }); closeCall(false); };
  const toggleMute = () => { const next = !muted; localStreamRef.current?.getAudioTracks().forEach((track) => { track.enabled = !next; }); setMuted(next); };
  useEffect(() => { if (state !== 'connected') return; const timer = window.setInterval(() => setElapsed((seconds) => seconds + 1), 1000); return () => window.clearInterval(timer); }, [state]);
  const time = `${Math.floor(elapsed / 60)}:${String(elapsed % 60).padStart(2, '0')}`;

  if (!active || !otherUserId) return <button type="button" className="chat-icon-button header-call" onClick={() => toast.info('Le profil du correspondant ne permet pas encore l’appel audio.')} aria-label="Appeler"><Phone /></button>;
  if (state === 'idle') return <><button type="button" className="chat-icon-button header-call" onClick={() => void startCall()} aria-label="Démarrer un appel audio IP"><Phone /></button><audio ref={remoteAudioRef} autoPlay playsInline /></>;
  if (state === 'incoming') return <div className="call-overlay"><div className="call-card incoming-call"><div className="call-avatar"><PhoneCall /></div><p>Appel audio entrant</p><strong>{otherName}</strong><div className="call-actions"><button type="button" className="call-action decline" onClick={declineCall}><PhoneOff /><span>Refuser</span></button><button type="button" className="call-action accept" onClick={acceptCall}><Phone /><span>Accepter</span></button></div></div><audio ref={remoteAudioRef} autoPlay playsInline /></div>;
  return <><button type="button" className="chat-icon-button header-call in-call" onClick={() => closeCall()} aria-label="Raccrocher"><PhoneOff /></button><div className="call-overlay"><div className="call-card"><div className="call-avatar call-avatar-live"><Volume2 /></div><p>{state === 'calling' ? 'Appel en cours…' : 'Appel audio Majay'}</p><strong>{otherName}</strong><span className="call-time">{state === 'connected' ? time : 'Connexion sécurisée'}</span><div className="call-actions"><button type="button" className="call-action mute" onClick={toggleMute}>{muted ? <MicOff /> : <Mic />}<span>{muted ? 'Activer' : 'Muet'}</span></button><button type="button" className="call-action decline" onClick={() => closeCall()}><PhoneOff /><span>Raccrocher</span></button></div></div><audio ref={remoteAudioRef} autoPlay playsInline /></div></>;
}
