'use client';

import { useEffect, useState } from 'react';
import { useRouterStore } from '@/stores/use-router-store';
import { useAuthStore } from '@/stores/use-auth-store';
import { ArrowLeft, Camera, Edit3, FileText, Grid3X3, Heart, LogOut, MapPin, MessageCircle, MoreHorizontal, Save, Settings, ShieldCheck, Store, X, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

export function ProfilePage() {
  const navigate = useRouterStore((s) => s.navigate); const { user, logout, setUser } = useAuthStore();
  const [listings, setListings] = useState<any[]>([]); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [avatarUploading, setAvatarUploading] = useState(false);
  const [form, setForm] = useState({ name: user?.name || '', phone: user?.phone || '', location: user?.location || '', bio: user?.bio || '', avatar: user?.avatar || '' });
  useEffect(() => { if (!user) { navigate('login'); return; } fetch('/api/listings?limit=100').then((r) => r.json()).then((d) => setListings((d.listings || []).filter((l: any) => l.sellerId === user.id))).catch(() => setListings([])); }, [user?.id, navigate]);
  if (!user) return null;
  const views = listings.reduce((sum, l) => sum + (l.views || 0), 0); const active = listings.filter((l) => l.status === 'active').length;
  const saveProfile = async () => { setSaving(true); try { const r = await fetch('/api/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'update-profile', ...form }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setUser(d.user); setEditing(false); toast.success('Profil mis à jour.'); } catch (e: any) { toast.error(e.message || 'Erreur'); } finally { setSaving(false); } };
  const uploadAvatar = async (file: File) => { if (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024) return toast.error('Image JPG, PNG ou WebP de 5 Mo maximum.'); setAvatarUploading(true); try { const fd = new FormData(); fd.append('file', file); const r = await fetch('/api/upload', { method: 'POST', body: fd }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setForm((f) => ({ ...f, avatar: d.url })); toast.success('Photo ajoutée. Enregistre ton profil.'); } catch (e: any) { toast.error(e.message || 'Upload impossible.'); } finally { setAvatarUploading(false); } };
  const openEdit = () => { setForm({ name: user.name || '', phone: user.phone || '', location: user.location || '', bio: user.bio || '', avatar: user.avatar || '' }); setEditing(true); };

  return <div className="social-profile pb-10">
    <section className="profile-cover"><div className="cover-pattern" /><button onClick={() => navigate('home')} className="profile-back"><ArrowLeft /></button><button className="profile-more" aria-label="Options"><MoreHorizontal /></button></section>
    <section className="profile-identity"><div className="profile-main-row"><label className="social-avatar"><input type="file" accept="image/*" className="sr-only" disabled={avatarUploading} onChange={(e) => { const f = e.target.files?.[0]; if (f) void uploadAvatar(f); e.currentTarget.value = ''; }} />{form.avatar || user.avatar ? <img src={form.avatar || user.avatar} alt="Photo de profil" /> : <span>{user.name?.[0] || 'U'}</span>}<i>{avatarUploading ? <Loader2 className="animate-spin" /> : <Camera />}</i></label><div className="profile-name-block"><div className="flex items-center gap-2"><h1>{user.name || 'Utilisateur'}</h1>{user.isVerifiedSeller && <ShieldCheck className="h-5 w-5 text-coral" />}</div><p>@{(user.name || 'majaay').toLowerCase().replace(/\s+/g, '')}</p></div><button onClick={openEdit} className="profile-edit"><Edit3 /> Modifier</button></div><p className="profile-bio">{user.bio || 'Bienvenue dans mon espace Majaay. Découvrez mes annonces et mes trouvailles.'}</p><div className="profile-meta"><span><MapPin /> {user.location || 'Sénégal'}</span><span><Store /> {user.subscriptionTier === 'free' ? 'Vendeur particulier' : `Vendeur ${user.subscriptionTier}`}</span></div><div className="profile-stats"><div><b>{active}</b><span>Annonces</span></div><div><b>{views}</b><span>Vues</span></div><div><b>{listings.length}</b><span>Publications</span></div></div></section>
    <nav className="profile-tabs"><button className="active"><Grid3X3 /> Publications</button><button onClick={() => navigate('my-listings')}><FileText /> Mes annonces</button><button onClick={() => navigate('plans')}><Heart /> Plans</button></nav>
    {editing && <section className="profile-editor"><div className="editor-title"><h2>Modifier le profil</h2><button onClick={() => setEditing(false)}><X /></button></div><input placeholder="Nom complet" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Téléphone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input placeholder="Ville ou localisation" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><textarea placeholder="Ta bio vendeur" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /><button onClick={() => void saveProfile()} disabled={saving} className="editor-save"><Save /> {saving ? 'Enregistrement…' : 'Enregistrer'}</button></section>}
    <section className="profile-feed"><div className="feed-heading"><div><span className="eyebrow">Ton activité</span><h2>Publications récentes</h2></div><button onClick={() => navigate('create-listing')}><Camera /> Publier</button></div>{listings.length === 0 ? <div className="profile-empty"><Store /><h3>Ton espace est prêt à vivre.</h3><p>Publie ta première annonce et construis ta vitrine Majaay.</p><button onClick={() => navigate('create-listing')}>Créer une annonce</button></div> : <div className="profile-grid">{listings.map((l) => { let img = ''; try { img = l.images && l.images !== '[]' ? JSON.parse(l.images)[0] : ''; } catch {} return <button key={l.id} onClick={() => navigate('listing-detail', { id: l.id })} className="profile-post">{img ? <img src={img} alt={l.title} /> : <div className="post-empty"><Store /></div>}<span>{l.title}</span></button>; })}</div>}</section>
    <button className="profile-logout" onClick={() => { logout(); navigate('home'); toast.success('Déconnecté'); }}><LogOut /> Se déconnecter</button>
  </div>;
}
