'use client';

import { useEffect, useState } from 'react';
import { useRouterStore } from '@/stores/use-router-store';
import { Search, SlidersHorizontal, X, MapPin, ShieldCheck, Zap, ArrowLeft, SearchX, Package } from 'lucide-react';
import { formatPrice } from './HomePage';

export function SearchPage() {
  const navigate = useRouterStore((s) => s.navigate); const { params } = useRouterStore();
  const [categories, setCategories] = useState<any[]>([]); const [listings, setListings] = useState<any[]>([]); const [search, setSearch] = useState(params.q || ''); const [selectedCategory, setSelectedCategory] = useState(params.categoryId || ''); const [selectedCity, setSelectedCity] = useState(''); const [sortBy, setSortBy] = useState('recent'); const [showFilters, setShowFilters] = useState(false); const [loading, setLoading] = useState(true); const [total, setTotal] = useState(0);
  useEffect(() => { fetch('/api/categories').then((r) => r.json()).then((d) => setCategories(Array.isArray(d) ? d : [])).catch(() => setCategories([])); }, []);
  useEffect(() => { let cancelled = false; const run = async () => { setLoading(true); const query = new URLSearchParams(); if (search) query.set('search', search); if (selectedCategory) query.set('categoryId', selectedCategory); if (selectedCity) query.set('city', selectedCity); query.set('sortBy', sortBy); query.set('limit', '50'); try { const data = await (await fetch(`/api/listings?${query}`)).json(); if (!cancelled) { setListings(Array.isArray(data?.listings) ? data.listings : []); setTotal(data?.total || 0); } } finally { if (!cancelled) setLoading(false); } }; void run(); return () => { cancelled = true; }; }, [search, selectedCategory, selectedCity, sortBy]);
  const clear = () => { setSearch(''); setSelectedCategory(''); setSelectedCity(''); setSortBy('recent'); };
  return <div className="signature-search px-4 pb-8 md:px-8 lg:px-12"><div className="search-heading"><button onClick={() => navigate('home')} className="back-circle"><ArrowLeft /></button><div><p className="eyebrow">Le marché en mouvement</p><h1>Explorer les trouvailles</h1></div></div><div className="signature-searchbar"><Search /><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && setSearch(e.currentTarget.value)} placeholder="Un téléphone, une voiture, une bonne adresse..." /><button onClick={() => setShowFilters(!showFilters)} className={showFilters ? 'filter-active' : ''}><SlidersHorizontal /> Filtres</button></div>{showFilters && <div className="filter-sheet"><div><span>Catégories</span><div className="filter-options">{categories.map((cat) => <button key={cat.id} onClick={() => setSelectedCategory(selectedCategory === cat.id ? '' : cat.id)} className={selectedCategory === cat.id ? 'selected' : ''}>{cat.name}</button>)}</div></div><div><span>Ville</span><div className="filter-options">{['Dakar', 'Pikine', 'Thiès', 'Rufisque', 'Saint-Louis'].map((city) => <button key={city} onClick={() => setSelectedCity(selectedCity === city ? '' : city)} className={selectedCity === city ? 'selected' : ''}>{city}</button>)}</div></div><div><span>Trier</span><div className="filter-options">{[['recent','Récent'],['popular','Populaire'],['price-asc','Prix croissant'],['price-desc','Prix décroissant']].map(([value,label]) => <button key={value} onClick={() => setSortBy(value)} className={sortBy === value ? 'selected' : ''}>{label}</button>)}</div></div>{(search || selectedCategory || selectedCity) && <button onClick={clear} className="clear-filters"><X /> Effacer les filtres</button>}</div>}<div className="results-meta"><span><b>{total}</b> résultat{total !== 1 ? 's' : ''}</span>{search && <span className="query-pill">« {search} »</span>}</div>{loading ? <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[1,2,3,4].map((n) => <div key={n} className="skeleton-card" />)}</div> : listings.length === 0 ? <div className="empty-market"><SearchX className="h-10 w-10 text-coral" /><h3>Aucune trouvaille pour l’instant.</h3><p>Essaie un autre mot-clé ou reviens bientôt : les meilleures annonces arrivent ici.</p></div> : <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{listings.map((listing, index) => <SearchCard key={listing.id} listing={listing} index={index} onOpen={() => navigate('listing-detail', { id: listing.id })} />)}</div>}</div>;
}

function SearchCard({ listing, index, onOpen }: { listing: any; index: number; onOpen: () => void }) { let image = null; try { image = listing.images && listing.images !== '[]' ? JSON.parse(listing.images)[0] : null; } catch {} return <article onClick={onOpen} className="new-listing-card" style={{ animationDelay: `${index * 35}ms` }}><div className="listing-visual">{image ? <img src={image} alt={listing.title} loading="lazy" /> : <div className="listing-placeholder"><Package className="h-8 w-8 text-coral/60" /></div>}{listing.isBoosted && <span className="boost-chip"><Zap className="h-3 w-3" /> Boost</span>}</div><div className="p-3.5"><h3 className="line-clamp-2 text-sm font-black leading-snug text-ink">{listing.title}</h3><p className="mt-2 text-base font-black text-coral">{formatPrice(listing.price)}</p><p className="mt-3 flex items-center gap-1 text-[10px] font-bold text-ink-soft"><MapPin className="h-3 w-3" />{listing.city || 'Sénégal'}{listing.seller?.isVerifiedSeller && <ShieldCheck className="ml-auto h-3.5 w-3.5 text-accent" />}</p></div></article>; }
